### ISSUE TITLE
No Weighting ?

### ISSUE THREAD

**Issue by Paul-Charpentier** [iastro-pt/gpyrn#10]
Hello ! It's me again :) 

I just wanted to know if there is a way to not use weighting just as we do for standard Gaussian Process Regression in the case of a single dataset ? 

I mean, this is possible by using a constant and fixed weighting but my question is can we use no weighting at all? 

Cheers. 
Paul

**Comment by jdavidrcamacho** [comment]
As it stand a GPRN cannot use a constant weighting  (or constant kernel) because the matrix used in the weight need to be inverted in the middle of the calculations, this is due to the Mean field variational inference used.
As far as not using weight at all, well you would end up with just a GP in that case and again you would ran into problems with the variational inference method we use. In our case, the variational inference used was specifically developed for the GPRN not a GP, e.g. unlike a GP  we dont use nor have a way to calculate the log likelihood. Removing or not using a weight would break all the calculations used.

**Comment by Paul-Charpentier** [comment]
Ok. Thanks :)

**Comment by jdavidrcamacho** [comment]
In any case if you are looking for something more similar to how a gp works check this package https://github.com/jdavidrcamacho/artgpn 
It might be what you are looking for
